name: Trigger Docs Generator

on:
  release:
    types:
      - published

permissions: write-all

concurrency:
  group: "docs"
  cancel-in-progress: true

jobs:
  trigger-generator:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger generator
      run: |
        echo ${{ JSON.stringify(github.event) }}
        curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.token }}" \
          https://api.github.com/repos/maxhr/near--docs/dispatches \
          -d '{"event_type":"release-publish","client_payload":{"source_repo":"maxhr/near--near-api-js","builder_name":"near-api-js","release_version":"${{ github.event.tag_name }}"}}'