name: Trigger Docs Generator

on:
  release:
    types:
      - published

concurrency:
  group: "docs"
  cancel-in-progress: true

jobs:
  trigger-generator:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger generator
      run: |
        curl -i -v --location --request POST 'https://docs-bot.vercel.app/api/on-release' \
        --header 'bot-auth: ${{ secrets.DOCS_BOT_SECRET }}' \
        --header 'Content-Type: application/json' \
        --data-raw '{
          "event_type": "release-publish",
          "client_payload": {
            "source_repo": "maxhr/near--near-api-js",
            "builder_name": "near-api-js",
            "release_version": "${{ github.ref_name }}"
          }
        }'