name: Trigger Docs Generator

on:
  release:
    types:
      - published

concurrency:
  group: "docs"
  cancel-in-progress: true

jobs:
  trigger-generator:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Trigger generator
      run: |
        curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.DOCS_GENERATOR_ACCESS_TOKEN }}" https://api.github.com/repos/maxhr/near--docs/dispatches -d '{"event_type":"release-publish","client_payload":{"source_repo":"maxhr/near--near-api-js","builder_name":"near-api-js","release_version":"${{ github.event.ref_name }}"}}'