name: Trigger Docs Generator

on:
  release:
    types:
      - published

concurrency:
  group: "docs"
  cancel-in-progress: true

jobs:
  trigger-generator:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger generator
      run: |
        curl -X POST -H "Authorization: Bearer ${{ secrets.DOCS_BOT_SECRET }}" https://docs-bot.vercel.app/on-release -d '{"event_type":"release-publish","client_payload":{"source_repo":"maxhr/near--near-api-js","builder_name":"near-api-js","release_version":"${{ github.ref_name }}"}}'